
'use client';

import Image from 'next/image';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ShoppingCart, Tag, Eye } from 'lucide-react';
import { siteConfig } from '@/config/site';

// Updated product list
const products = [
  {
    id: "prod_adh_001",
    name: "Adhesive",
    description: "General purpose construction adhesive.",
    price: 18000,
    category: "Adhesives & Sealants",
    imageUrl: "https://placehold.co/600x400.png?text=Adhesive",
    dataAiHint: "adhesive tube",
    stock: 150,
    rating: 4.4,
    reviews: 60,
  },
  {
    id: "prod_reinf_004",
    name: "BRC Mesh",
    description: "Welded steel fabric for concrete reinforcement.",
    price: 350000,
    category: "Reinforcement",
    imageUrl: "https://placehold.co/600x400.png?text=BRC+Mesh",
    dataAiHint: "steel mesh roll",
    stock: 30,
    rating: 4.6,
    reviews: 45,
  },
  {
    id: "prod_painttool_001",
    name: "Baby Roller",
    description: "Small paint roller for detailed work.",
    price: 5000,
    category: "Painting Tools",
    imageUrl: "https://placehold.co/600x400.png?text=Baby+Roller",
    dataAiHint: "paint roller small",
    stock: 200,
    rating: 4.3,
    reviews: 90,
  },
  {
    id: "prod_fence_003",
    name: "Barbed Wire",
    description: "Galvanized barbed wire for security fencing.",
    price: 145000,
    category: "Fencing",
    imageUrl: "https://placehold.co/600x400.png?text=Barbed+Wire",
    dataAiHint: "barbed wire coil",
    stock: 60,
    rating: 4.5,
    reviews: 70,
  },
  {
    id: "prod_plumb_003",
    name: "Bend (Pipe Fitting)",
    description: "Pipe bend for plumbing and drainage systems.",
    price: 6000,
    category: "Plumbing & Drainage",
    imageUrl: "https://placehold.co/600x400.png?text=Pipe+Bend",
    dataAiHint: "pipe fitting bend",
    stock: 250,
    rating: 4.2,
    reviews: 50,
  },
  {
    id: "prod_roof_002",
    name: "Bull Nose Sheets",
    description: "Curved roofing sheets for aesthetic finishes.",
    price: 39000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Bull+Nose+Sheet",
    dataAiHint: "bullnose roofing sheet",
    stock: 100,
    rating: 4.6,
    reviews: 30,
  },
  {
    id: "prod_board_001",
    name: "Ceiling Board",
    description: "Standard ceiling boards for interior finishing.",
    price: 30000,
    category: "Boards & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Ceiling+Board",
    dataAiHint: "ceiling panel",
    stock: 300,
    rating: 4.4,
    reviews: 80,
  },
  {
    id: "prod_fast_002",
    name: "Ceiling Nails (1kg)",
    description: "Specialized nails for fixing ceiling boards.",
    price: 12000,
    category: "Fasteners",
    imageUrl: "https://placehold.co/600x400.png?text=Ceiling+Nails",
    dataAiHint: "nails box",
    stock: 180,
    rating: 4.3,
    reviews: 65,
  },
  {
    id: "prod_cem_001",
    name: "Cement (50kg Bag)",
    description: "General purpose Portland cement.",
    price: 32000,
    category: "Cement",
    imageUrl: "https://placehold.co/600x400.png?text=Cement",
    dataAiHint: "cement bag",
    stock: 500,
    rating: 4.7,
    reviews: 250,
  },
  {
    id: "prod_fence_004",
    name: "Chain Link Fence",
    description: "Galvanized chain link fencing material.",
    price: 180000,
    category: "Fencing",
    imageUrl: "https://placehold.co/600x400.png?text=Chain+Link",
    dataAiHint: "chain link fence roll",
    stock: 40,
    rating: 4.6,
    reviews: 55,
  },
  {
    id: "prod_gutter_001",
    name: "Clips (Gutters)",
    description: "Fixing clips for gutter installation.",
    price: 2500,
    category: "Plumbing & Drainage",
    imageUrl: "https://placehold.co/600x400.png?text=Gutter+Clips",
    dataAiHint: "gutter clip",
    stock: 400,
    rating: 4.1,
    reviews: 30,
  },
  {
    id: "prod_fast_003",
    name: "Concrete Nails (1kg)",
    description: "Hardened steel nails for concrete applications.",
    price: 5000,
    category: "Fasteners",
    imageUrl: "https://placehold.co/600x400.png?text=Concrete+Nails",
    dataAiHint: "concrete nails",
    stock: 300,
    rating: 4.5,
    reviews: 110,
  },
  {
    id: "prod_fittings_001",
    name: "Connector (Facial Board)",
    description: "Connectors for joining facial boards.",
    price: 12000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Facial+Connector",
    dataAiHint: "board connector",
    stock: 150,
    rating: 4.3,
    reviews: 20,
  },
  {
    id: "prod_gutter_002",
    name: "Connectors (Gutters)",
    description: "Connectors for joining gutter sections.",
    price: 8000,
    category: "Plumbing & Drainage",
    imageUrl: "https://placehold.co/600x400.png?text=Gutter+Connector",
    dataAiHint: "gutter connector",
    stock: 200,
    rating: 4.2,
    reviews: 25,
  },
  {
    id: "prod_fittings_002",
    name: "Corners (Facial Board)",
    description: "Corner pieces for facial board installations.",
    price: 22000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Facial+Corner",
    dataAiHint: "board corner",
    stock: 100,
    rating: 4.4,
    reviews: 15,
  },
  {
    id: "prod_gutter_003",
    name: "Corners (Gutters)",
    description: "Corner pieces for gutter systems.",
    price: 8000,
    category: "Plumbing & Drainage",
    imageUrl: "https://placehold.co/600x400.png?text=Gutter+Corner",
    dataAiHint: "gutter corner piece",
    stock: 180,
    rating: 4.3,
    reviews: 22,
  },
  {
    id: "prod_fittings_003",
    name: "End Caps (Generic)",
    description: "End caps for various finishing purposes.",
    price: 2500,
    category: "Fittings",
    imageUrl: "https://placehold.co/600x400.png?text=End+Caps",
    dataAiHint: "pipe end cap",
    stock: 300,
    rating: 4.0,
    reviews: 18,
  },
  {
    id: "prod_roof_003",
    name: "Endcap (Versatile)",
    description: "Endcap for versatile roofing sheets.",
    price: 10000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Versatile+Endcap",
    dataAiHint: "roofing endcap",
    stock: 120,
    rating: 4.5,
    reviews: 10,
  },
  {
    id: "prod_constmat_001",
    name: "Expanded Metal Lath",
    description: "Metal lath for plastering and reinforcement.",
    price: 35000,
    category: "Construction Materials",
    imageUrl: "https://placehold.co/600x400.png?text=Metal+Lath",
    dataAiHint: "expanded metal sheet",
    stock: 80,
    rating: 4.4,
    reviews: 25,
  },
  {
    id: "prod_board_002",
    name: "Facial Board",
    description: "Boards for facial and soffit applications.",
    price: 66000,
    category: "Boards & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Facial+Board",
    dataAiHint: "construction board",
    stock: 90,
    rating: 4.5,
    reviews: 20,
  },
  {
    id: "prod_tiles_001",
    name: "Floor Tiles (Sqm)",
    description: "Standard ceramic floor tiles, price per square meter.",
    price: 25000,
    category: "Tiles",
    imageUrl: "https://placehold.co/600x400.png?text=Floor+Tiles",
    dataAiHint: "ceramic floor tiles",
    stock: 500,
    rating: 4.6,
    reviews: 120,
  },
  {
    id: "prod_finish_001",
    name: "Grout (1kg)",
    description: "Tile grout for filling gaps between tiles.",
    price: 15000,
    category: "Tiling Accessories",
    imageUrl: "https://placehold.co/600x400.png?text=Grout",
    dataAiHint: "grout powder bag",
    stock: 100,
    rating: 4.3,
    reviews: 40,
  },
  {
    id: "prod_gutter_004",
    name: "Gutters (Per Length)",
    description: "Rainwater gutters for roofing systems.",
    price: 28000,
    category: "Plumbing & Drainage",
    imageUrl: "https://placehold.co/600x400.png?text=Gutters",
    dataAiHint: "rain gutter section",
    stock: 150,
    rating: 4.5,
    reviews: 35,
  },
  {
    id: "prod_solar_001",
    name: "Inverter Hybrid",
    description: "Hybrid solar inverter for power systems.",
    price: 1490000,
    category: "Solar & Electrical",
    imageUrl: "https://placehold.co/600x400.png?text=Hybrid+Inverter",
    dataAiHint: "solar inverter",
    stock: 10,
    rating: 4.8,
    reviews: 15,
  },
  {
    id: "prod_roof_004",
    name: "Ironsheets (Galvanized)",
    description: "Standard galvanized iron roofing sheets.",
    price: 34000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Galvanized+Sheet",
    dataAiHint: "metal roofing sheet",
    stock: 400,
    rating: 4.4,
    reviews: 90,
  },
  {
    id: "prod_roof_005",
    name: "Ironsheets (Prepainted)",
    description: "Prepainted iron roofing sheets, various colors.",
    price: 40900,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Prepainted+Sheet",
    dataAiHint: "colored roofing sheet",
    stock: 300,
    rating: 4.6,
    reviews: 70,
  },
  {
    id: "prod_solar_002",
    name: "Lithium Battery",
    description: "High-capacity lithium battery for solar systems.",
    price: 990000,
    category: "Solar & Electrical",
    imageUrl: "https://placehold.co/600x400.png?text=Lithium+Battery",
    dataAiHint: "solar battery",
    stock: 15,
    rating: 4.7,
    reviews: 20,
  },
  {
    id: "prod_board_003",
    name: "Marine Board",
    description: "Water-resistant marine plywood board.",
    price: 1, // Placeholder price
    category: "Boards & Timber",
    imageUrl: "https://placehold.co/600x400.png?text=Marine+Board",
    dataAiHint: "plywood sheet",
    stock: 50,
    rating: 4.5,
    reviews: 10,
  },
  {
    id: "prod_toolacc_001",
    name: "Masking Tape",
    description: "Painter's masking tape for clean edges.",
    price: 2000,
    category: "Painting Accessories",
    imageUrl: "https://placehold.co/600x400.png?text=Masking+Tape",
    dataAiHint: "masking tape roll",
    stock: 500,
    rating: 4.2,
    reviews: 150,
  },
  {
    id: "prod_elec_002",
    name: "Outlet (Electrical)",
    description: "Electrical wall outlet/socket.",
    price: 1, // Placeholder price
    category: "Solar & Electrical",
    imageUrl: "https://placehold.co/600x400.png?text=Electrical+Outlet",
    dataAiHint: "wall socket",
    stock: 200,
    rating: 4.3,
    reviews: 40,
  },
  {
    id: "prod_finish_002",
    name: "Paste (Texture)",
    description: "Textured wall paste for decorative finishes.",
    price: 180000,
    category: "Paints & Finishes",
    imageUrl: "https://placehold.co/600x400.png?text=Texture+Paste",
    dataAiHint: "paint paste bucket",
    stock: 30,
    rating: 4.6,
    reviews: 25,
  },
  {
    id: "prod_plumb_004",
    name: "Pipe Clips",
    description: "Clips for securing pipes to walls or surfaces.",
    price: 2000,
    category: "Plumbing & Drainage",
    imageUrl: "https://placehold.co/600x400.png?text=Pipe+Clips",
    dataAiHint: "pipe support clip",
    stock: 600,
    rating: 4.1,
    reviews: 70,
  },
  {
    id: "prod_plumb_005",
    name: "Pipes (PVC/Metal, Per Length)",
    description: "Various types of pipes for plumbing or construction.",
    price: 23000,
    category: "Plumbing & Drainage",
    imageUrl: "https://placehold.co/600x400.png?text=Pipes",
    dataAiHint: "pvc pipes stack",
    stock: 400,
    rating: 4.4,
    reviews: 60,
  },
  {
    id: "prod_roof_006",
    name: "Plain Sheets (Galvanized)",
    description: "Flat galvanized plain sheets for various uses.",
    price: 110000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Plain+Sheet",
    dataAiHint: "flat metal sheet",
    stock: 70,
    rating: 4.3,
    reviews: 30,
  },
  {
    id: "prod_fence_005",
    name: "Plain Wire (Roll)",
    description: "Galvanized plain wire for fencing or general use.",
    price: 8000, // Price seems low for a roll, might be per kg or smaller roll.
    category: "Fencing",
    imageUrl: "https://placehold.co/600x400.png?text=Plain+Wire",
    dataAiHint: "wire coil plain",
    stock: 200,
    rating: 4.2,
    reviews: 40,
  },
  {
    id: "prod_fence_006",
    name: "Razor Wire (Roll)",
    description: "Concertina razor wire for high-security fencing.",
    price: 35000,
    category: "Fencing",
    imageUrl: "https://placehold.co/600x400.png?text=Razor+Wire",
    dataAiHint: "razor wire coil",
    stock: 50,
    rating: 4.7,
    reviews: 20,
  },
  {
    id: "prod_reinf_001",
    name: "Reinforcement Steel (Y-grade, Per Length)",
    description: "High tensile deformed steel bars for structural reinforcement.",
    price: 45000,
    category: "Reinforcement",
    imageUrl: "https://placehold.co/600x400.png?text=Steel+Bar",
    dataAiHint: "steel rebar",
    stock: 300,
    rating: 4.7,
    reviews: 90,
  },
  {
    id: "prod_roof_007",
    name: "Ridges (Standard)",
    description: "Standard roofing ridges for apex covering.",
    price: 16500,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Roof+Ridge",
    dataAiHint: "roof ridge cap",
    stock: 200,
    rating: 4.4,
    reviews: 40,
  },
  {
    id: "prod_roof_008",
    name: "Ridges (Versatile)",
    description: "Versatile roofing ridges for specific sheet profiles.",
    price: 29000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Versatile+Ridge",
    dataAiHint: "special roof ridge",
    stock: 100,
    rating: 4.5,
    reviews: 15,
  },
  {
    id: "prod_painttool_002",
    name: "Roller Brush",
    description: "Standard paint roller brush.",
    price: 10000,
    category: "Painting Tools",
    imageUrl: "https://placehold.co/600x400.png?text=Roller+Brush",
    dataAiHint: "paint roller large",
    stock: 150,
    rating: 4.4,
    reviews: 100,
  },
  {
    id: "prod_fast_001",
    name: "Roofing Nails (1kg)",
    description: "Galvanized twisted shank roofing nails.",
    price: 8000,
    category: "Fasteners",
    imageUrl: "https://placehold.co/600x400.png?text=Roofing+Nails",
    dataAiHint: "roofing nails",
    stock: 200,
    rating: 4.5,
    reviews: 100,
  },
  {
    id: "prod_fast_004",
    name: "Rubber Washers (Pack)",
    description: "Rubber washers for roofing nails.",
    price: 7000,
    category: "Fasteners",
    imageUrl: "https://placehold.co/600x400.png?text=Rubber+Washers",
    dataAiHint: "rubber washers pack",
    stock: 300,
    rating: 4.2,
    reviews: 80,
  },
  {
    id: "prod_toolacc_002",
    name: "Sand Paper (Sheet)",
    description: "Abrasive sandpaper for smoothing surfaces.",
    price: 2500,
    category: "Tools & Accessories",
    imageUrl: "https://placehold.co/600x400.png?text=Sand+Paper",
    dataAiHint: "sandpaper sheet",
    stock: 1000,
    rating: 4.3,
    reviews: 120,
  },
  {
    id: "prod_tools_004",
    name: "Scraper",
    description: "Paint scraper for surface preparation.",
    price: 5000,
    category: "Tools",
    imageUrl: "https://placehold.co/600x400.png?text=Scraper",
    dataAiHint: "paint scraper tool",
    stock: 100,
    rating: 4.1,
    reviews: 60,
  },
  {
    id: "prod_fast_005",
    name: "Self Tapping Screws (Box)",
    description: "Self-tapping screws for metal applications.",
    price: 69000,
    category: "Fasteners",
    imageUrl: "https://placehold.co/600x400.png?text=Self+Tapping+Screws",
    dataAiHint: "screws box",
    stock: 80,
    rating: 4.6,
    reviews: 30,
  },
  {
    id: "prod_outdoor_001",
    name: "Shade Net (Roll)",
    description: "Shade netting for agricultural or construction use.",
    price: 279000,
    category: "Outdoor & Garden",
    imageUrl: "https://placehold.co/600x400.png?text=Shade+Net",
    dataAiHint: "shade net roll",
    stock: 20,
    rating: 4.5,
    reviews: 10,
  },
  {
    id: "prod_paint_001",
    name: "Silk Vinyl Paint (Indoor, 20L)",
    description: "Premium silk vinyl emulsion paint for interiors.",
    price: 350000,
    category: "Paints & Finishes",
    imageUrl: "https://placehold.co/600x400.png?text=Silk+Vinyl+Paint",
    dataAiHint: "paint bucket large",
    stock: 40,
    rating: 4.8,
    reviews: 30,
  },
  {
    id: "prod_solar_003",
    name: "Solar Controller",
    description: "Charge controller for solar panel systems.",
    price: 1, // Placeholder price
    category: "Solar & Electrical",
    imageUrl: "https://placehold.co/600x400.png?text=Solar+Controller",
    dataAiHint: "solar charge controller",
    stock: 25,
    rating: 4.6,
    reviews: 12,
  },
  {
    id: "prod_solar_004",
    name: "Solar Panels (Per Unit)",
    description: "Photovoltaic solar panels for energy generation.",
    price: 490000,
    category: "Solar & Electrical",
    imageUrl: "https://placehold.co/600x400.png?text=Solar+Panel",
    dataAiHint: "solar panel",
    stock: 30,
    rating: 4.7,
    reviews: 25,
  },
  {
    id: "prod_solar_005",
    name: "Solar Pump",
    description: "Solar-powered water pump.",
    price: 590000,
    category: "Solar & Electrical",
    imageUrl: "https://placehold.co/600x400.png?text=Solar+Pump",
    dataAiHint: "solar water pump",
    stock: 8,
    rating: 4.5,
    reviews: 8,
  },
  {
    id: "prod_tileacc_002",
    name: "Spacers (Tile Spacers, Pack)",
    description: "Plastic spacers for uniform tile gaps.",
    price: 5000,
    category: "Tiling Accessories",
    imageUrl: "https://placehold.co/600x400.png?text=Tile+Spacers",
    dataAiHint: "tile spacers pack",
    stock: 500,
    rating: 4.3,
    reviews: 70,
  },
  {
    id: "prod_constmat_002",
    name: "Strips (Wooden/Metal)",
    description: "Strips for various construction applications.",
    price: 9000,
    category: "Construction Materials",
    imageUrl: "https://placehold.co/600x400.png?text=Strips",
    dataAiHint: "wooden strips",
    stock: 200,
    rating: 4.2,
    reviews: 30,
  },
  {
    id: "prod_fast_006",
    name: "U-Nails (1kg)",
    description: "U-shaped nails for fixing wire or mesh.",
    price: 1, // Placeholder price, seems too low
    category: "Fasteners",
    imageUrl: "https://placehold.co/600x400.png?text=U-Nails",
    dataAiHint: "u nails pack",
    stock: 100,
    rating: 4.0,
    reviews: 20,
  },
  {
    id: "prod_paint_002",
    name: "Undercoat Paint (20L)",
    description: "Primer or undercoat paint for surface preparation.",
    price: 60000,
    category: "Paints & Finishes",
    imageUrl: "https://placehold.co/600x400.png?text=Undercoat+Paint",
    dataAiHint: "paint bucket primer",
    stock: 70,
    rating: 4.4,
    reviews: 50,
  },
  {
    id: "prod_roof_009",
    name: "Valley Sheets",
    description: "Roofing sheets for valley sections of a roof.",
    price: 21000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Valley+Sheet",
    dataAiHint: "roof valley flashing",
    stock: 90,
    rating: 4.3,
    reviews: 10,
  },
  {
    id: "prod_roof_010",
    name: "Versatile Sheets",
    description: "Multi-purpose versatile roofing sheets.",
    price: 69000,
    category: "Roofing & Sheeting",
    imageUrl: "https://placehold.co/600x400.png?text=Versatile+Sheet",
    dataAiHint: "special roofing sheet",
    stock: 60,
    rating: 4.6,
    reviews: 20,
  },
  {
    id: "prod_tiles_002",
    name: "Wall Tiles (Sqm)",
    description: "Ceramic wall tiles, price per square meter.",
    price: 45000,
    category: "Tiles",
    imageUrl: "https://placehold.co/600x400.png?text=Wall+Tiles",
    dataAiHint: "ceramic wall tiles",
    stock: 400,
    rating: 4.5,
    reviews: 100,
  },
  {
    id: "prod_paint_003",
    name: "Weather Guard Paint (Outdoor, 20L)",
    description: "Durable exterior paint for weather protection.",
    price: 384000,
    category: "Paints & Finishes",
    imageUrl: "https://placehold.co/600x400.png?text=Weather+Guard+Paint",
    dataAiHint: "exterior paint bucket",
    stock: 35,
    rating: 4.9,
    reviews: 40,
  },
  {
    id: "prod_tools_003",
    name: "Wheelbarrow",
    description: "Construction grade wheelbarrow for transporting materials.",
    price: 145000,
    category: "Tools",
    imageUrl: "https://placehold.co/600x400.png?text=Wheelbarrow",
    dataAiHint: "wheelbarrow construction",
    stock: 30,
    rating: 4.7,
    reviews: 45,
  },
  {
    id: "prod_fast_007",
    name: "Wire Nails (1kg)",
    description: "Common wire nails for general construction.",
    price: 5000,
    category: "Fasteners",
    imageUrl: "https://placehold.co/600x400.png?text=Wire+Nails",
    dataAiHint: "nails common pack",
    stock: 1000,
    rating: 4.2,
    reviews: 200,
  },
];

export default function ShopPage() {
  return (
    <div className="space-y-12">
      <section className="text-center fade-in">
        <h1 className="font-headline text-4xl font-bold tracking-tight sm:text-5xl">Hardware & Materials Shop</h1>
        <p className="mt-4 max-w-2xl mx-auto text-lg text-muted-foreground">
          Browse our selection of high-quality construction hardware, tools, and materials. All prices in Ugandan Shillings (UGX).
          Full e-commerce functionality with cart, checkout, and various payment options is under development.
        </p>
      </section>

      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 fade-in" style={{animationDelay: '0.2s'}}>
        {products.map((product, index) => (
          <Card key={product.id} className="flex flex-col overflow-hidden group hover:shadow-xl transition-shadow duration-300 ease-in-out fade-in" style={{animationDelay: `${index * 0.05 + 0.2}s`}}>
            <div className="aspect-[4/3] overflow-hidden relative">
              <Image
                src={product.imageUrl}
                alt={product.name}
                fill
                sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, (max-width: 1280px) 33vw, 25vw"
                className="object-cover group-hover:scale-105 transition-transform duration-300"
                data-ai-hint={product.dataAiHint}
                priority={index < 8} 
              />
              <Badge variant="secondary" className="absolute top-2 right-2">{product.category}</Badge>
              <div className="absolute inset-0 bg-black/30 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                <Button variant="outline" size="sm" className="text-white border-white hover:bg-white/20" onClick={() => alert('Product page coming soon!')}>
                  <Eye className="mr-2 h-4 w-4" /> Quick View
                </Button>
              </div>
            </div>
            <CardHeader>
              <CardTitle className="font-headline text-lg h-14 overflow-hidden">
                {product.name}
              </CardTitle>
            </CardHeader>
            <CardContent className="flex-grow">
              <div className="flex items-center justify-between mb-2">
                <p className="text-xl font-semibold text-primary flex items-center">
                  <Tag className="h-5 w-5 mr-1.5 text-accent" />
                  UGX {product.price.toLocaleString()}
                </p>
                <Badge variant={product.stock > 0 ? "default" : "destructive"} className={product.stock > 0 ? "bg-green-600 hover:bg-green-700" : ""}>
                  {product.stock > 0 ? `${product.stock} in stock` : "Out of Stock"}
                </Badge>
              </div>
               <p className="text-xs text-muted-foreground min-h-[3lh]">{product.description}</p> {/* min-h for consistent card height */}
            </CardContent>
            <CardFooter className="flex-col items-stretch space-y-2">
              <Button className="w-full bg-primary hover:bg-primary/90" disabled={product.stock === 0} onClick={() => alert('Adding to cart functionality coming soon!')}>
                <ShoppingCart className="mr-2 h-4 w-4" />
                Add to Cart
              </Button>
               <Button variant="link" asChild className="text-primary p-0 text-sm">
                 <Link href="/services#hardware-supply">Quality & Benefits</Link>
               </Button>
            </CardFooter>
          </Card>
        ))}
      </section>
       <p className="text-center text-muted-foreground text-sm fade-in" style={{animationDelay: '0.4s'}}>
        Note: Product search, filtering, individual product pages, cart, and checkout functionalities are currently under development. For purchases or inquiries, please <Link href="/contact" className="text-primary hover:underline">contact us</Link>.
      </p>
    </div>
  );
}
